@Library('cb-days@master') _
pipeline {
  agent none
  triggers {
    eventTrigger jmespathQuery("event=='imagePush' && name=='node'")
  }
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
    timeout(time: 30, unit: 'MINUTES')
  }
  environment {
    repoOwner = "${repoOwner}"
    credId = "${githubCredentialId}"
  }
  stages('VueJS Test and Build')
  {
    stage('VueJS Tests') {
      agent {
        label 'nodejs'
      }
      steps {
        checkout scm
        gitShortCommit()
        container('nodejs') {
          sh '''
             yarn install
             yarn test:unit
             '''
        }
        stash name: "install", includes: "**/**"
        stash name: "k8s-deploy", includes: ".kubernetes/**"
      } 
      post {
        always {
          junit 'output/coverage/junit/junit.xml'
        }
      }
    }  
    stage('Node Image Push') {
      agent any
      when {
        allOf {
          branch 'master'
          triggeredBy 'EventTriggerCause' 
        }
      }
      steps {
        getImageBuildEventPayload()
      }
    }
    stage('Build and Push Image') {
      when {
        beforeAgent true
        branch 'master'
      }
      steps {
        imgBuildNexus("microblog-frontend", "${repoOwner}", "${registry}") {
          checkout scm
          gitShortCommit()
          stash name: "k8s-deploy", includes: ".kubernetes/**"
        }
      }
    }
    stage('Deploy'){
      when {
        beforeAgent true
        branch 'master'
      }
      // options {
      //   timeout(time: 90, unit: 'SECONDS') 
      // }
      steps {
        //input(message: "Should we deploy?", ok: "Deploy", submitterParameter: "APPROVER")
        blogKubeDeploy("${repository}", "${repoOwner}", "${registry}", "${deploymentDomain}") {
          unstash "k8s-deploy"
        }
      }
    }  
  }
}

